// Project Euler: Problem 2: Even Fibonacci NumbersPassed
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

function fiboEvenSum(n) {

  let arr=[1,2]; 
  let sum=2;
  
  if(n<=1){
    return 0;
  }

//crear array con la secuencia fibonacii
  for(let i = 2; i<n;i++){
   arr.push(arr[i-1]+arr[i-2])

//sumar pares
    if(arr[i]%2 == 0){
      sum += arr[i];
     }
  }

 return sum;
}

console.log(fiboEvenSum(1));
